title: Ty Carlson | designer, developer, husband, and friend
email: tywayne@gmail.com
description: My name is Ty Carlson and I am a designer, developer, husband, father, and friend.

version: '1.3.2'

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tywayne.com"
cdn_url: "https://dzgsio58p4nbe.cloudfront.net"
google_analytics: UA-11264448-3

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
    posts:
        output: true
        permalink: /blog/:title/
    links:
        output: false
    portfolio:
        output: false
    book_reviews:
        output: true
        permalink: /book-reviews/:title/

gems:
    - jekyll-feed
    - jekyll-minifier
    - jekyll-coffeescript
    - jekyll-sitemap
exclude:
    - Gemfile
    - Gemfile.lock

jekyll-minifier:
    exclude: ['htaccess', '.htaccess']