# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ty Carlson | designer, developer, husband, and friend
email: tywayne@gmail.com
description: My name is Ty Carlson and I am a designer, developer, husband, and friend.

version: '1.1.0'

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tywayne.com"
cdn_url: "https://dzgsio58p4nbe.cloudfront.net"

twitter_username:   tywayne
github_username:    tywayne
facebook_username:  tywayne
instagram_username: tywayne
spotify_username:   tywayne
dribbble_username:  tywayne

google_analytics: UA-11264448-3

# Build settings
markdown: kramdown

collections:
    links:
        output: false
    portfolio:
        output: false

gems:
    - jekyll-feed
    - normalize-scss
    - jekyll-minifier
exclude:
    - Gemfile
    - Gemfile.lock

jekyll-minifier:
exclude: ['htaccess', '.htaccess']