---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _photography
  label: Photography
  create: all
  match: "**/*"
- type: directory
  path: _reading_list
  label: Reading list
  create: all
  match: "**/*"
- type: directory
  path: _book_reviews
  label: Book reviews
  create: all
  match: "**/*"
- type: directory
  path: _portfolio
  label: Portfolio
  create: all
  match: "**/*"
- type: directory
  path: _links
  label: Links
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
